### ISSUE TITLE
Problemas para centrar pantalla

### ISSUE THREAD

**Issue by OrianaToscano** [PioIX/G12-TPI-1CUAT#7]
En cuanto a la pantalla de juego, esta se centra correctamente en ciertos tamaños de pantalla, sin embargo, en algunas medidas de ancho determinadas, el margen izquierdo del juego es mayor que el derecho, llevando a un scroll mayor innecesario. No afecta jugabilidad (ya no se corta la pantalla), pero es un detalle molesto. No sé por que puede estar pasando :(

**Comment by LaraPuelman** [comment]
oki, jaja q gravioso el help wanted

**Comment by fegerva2** [comment]
> oki, jaja q gravioso el help wanted

que gracioso el ***graVioso***

**Comment by OrianaToscano** [comment]
Solucionado en la actual versión del Replit (falta commitear cambios al repo de github)
